# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_lake.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(644, 524)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 480, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.isL_Lake_N = QtGui.QLineEdit(Dialog)
        self.isL_Lake_N.setGeometry(QtCore.QRect(280, 120, 61, 20))
        self.isL_Lake_N.setObjectName(_fromUtf8("isL_Lake_N"))
        self.L_LakeQmecsHEPP = QtGui.QLineEdit(Dialog)
        self.L_LakeQmecsHEPP.setGeometry(QtCore.QRect(560, 290, 61, 20))
        self.L_LakeQmecsHEPP.setObjectName(_fromUtf8("L_LakeQmecsHEPP"))
        self.label_155 = QtGui.QLabel(Dialog)
        self.label_155.setGeometry(QtCore.QRect(410, 260, 111, 16))
        self.label_155.setObjectName(_fromUtf8("label_155"))
        self.isL_Lake_Q = QtGui.QLineEdit(Dialog)
        self.isL_Lake_Q.setGeometry(QtCore.QRect(280, 210, 61, 20))
        self.isL_Lake_Q.setObjectName(_fromUtf8("isL_Lake_Q"))
        self.label_153 = QtGui.QLabel(Dialog)
        self.label_153.setGeometry(QtCore.QRect(410, 200, 111, 16))
        self.label_153.setObjectName(_fromUtf8("label_153"))
        self.label_157 = QtGui.QLabel(Dialog)
        self.label_157.setGeometry(QtCore.QRect(410, 320, 111, 16))
        self.label_157.setObjectName(_fromUtf8("label_157"))
        self.isL_Lake_S = QtGui.QLineEdit(Dialog)
        self.isL_Lake_S.setGeometry(QtCore.QRect(280, 270, 61, 20))
        self.isL_Lake_S.setObjectName(_fromUtf8("isL_Lake_S"))
        self.label_152 = QtGui.QLabel(Dialog)
        self.label_152.setGeometry(QtCore.QRect(410, 170, 111, 16))
        self.label_152.setObjectName(_fromUtf8("label_152"))
        self.label_67 = QtGui.QLabel(Dialog)
        self.label_67.setGeometry(QtCore.QRect(210, 270, 61, 16))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.L_LakeTransMultiplier = QtGui.QLineEdit(Dialog)
        self.L_LakeTransMultiplier.setGeometry(QtCore.QRect(560, 50, 61, 20))
        self.L_LakeTransMultiplier.setObjectName(_fromUtf8("L_LakeTransMultiplier"))
        self.L_LakeQmecsSanFlow = QtGui.QLineEdit(Dialog)
        self.L_LakeQmecsSanFlow.setGeometry(QtCore.QRect(560, 320, 61, 20))
        self.L_LakeQmecsSanFlow.setObjectName(_fromUtf8("L_LakeQmecsSanFlow"))
        self.label_64 = QtGui.QLabel(Dialog)
        self.label_64.setGeometry(QtCore.QRect(210, 240, 61, 16))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.label_72 = QtGui.QLabel(Dialog)
        self.label_72.setGeometry(QtCore.QRect(410, 20, 91, 16))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.isL_Lake_M = QtGui.QLineEdit(Dialog)
        self.isL_Lake_M.setGeometry(QtCore.QRect(280, 90, 61, 20))
        self.isL_Lake_M.setObjectName(_fromUtf8("isL_Lake_M"))
        self.label_160 = QtGui.QLabel(Dialog)
        self.label_160.setGeometry(QtCore.QRect(410, 410, 111, 16))
        self.label_160.setObjectName(_fromUtf8("label_160"))
        self.label_57 = QtGui.QLabel(Dialog)
        self.label_57.setGeometry(QtCore.QRect(20, 180, 61, 16))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.label_158 = QtGui.QLabel(Dialog)
        self.label_158.setGeometry(QtCore.QRect(410, 350, 111, 16))
        self.label_158.setObjectName(_fromUtf8("label_158"))
        self.label_161 = QtGui.QLabel(Dialog)
        self.label_161.setGeometry(QtCore.QRect(410, 440, 111, 16))
        self.label_161.setObjectName(_fromUtf8("label_161"))
        self.label_58 = QtGui.QLabel(Dialog)
        self.label_58.setGeometry(QtCore.QRect(20, 240, 61, 16))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.isL_Lake_O = QtGui.QLineEdit(Dialog)
        self.isL_Lake_O.setGeometry(QtCore.QRect(280, 150, 61, 20))
        self.isL_Lake_O.setObjectName(_fromUtf8("isL_Lake_O"))
        self.L_m3_per_kwh = QtGui.QLineEdit(Dialog)
        self.L_m3_per_kwh.setGeometry(QtCore.QRect(560, 410, 61, 20))
        self.L_m3_per_kwh.setObjectName(_fromUtf8("L_m3_per_kwh"))
        self.isL_Lake_F = QtGui.QLineEdit(Dialog)
        self.isL_Lake_F.setGeometry(QtCore.QRect(110, 180, 61, 20))
        self.isL_Lake_F.setObjectName(_fromUtf8("isL_Lake_F"))
        self.label_63 = QtGui.QLabel(Dialog)
        self.label_63.setGeometry(QtCore.QRect(210, 300, 61, 16))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_73 = QtGui.QLabel(Dialog)
        self.label_73.setGeometry(QtCore.QRect(410, 80, 111, 16))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.label_59 = QtGui.QLabel(Dialog)
        self.label_59.setGeometry(QtCore.QRect(20, 150, 61, 16))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_61 = QtGui.QLabel(Dialog)
        self.label_61.setGeometry(QtCore.QRect(20, 300, 61, 16))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.L_LakeFloodTresh = QtGui.QLineEdit(Dialog)
        self.L_LakeFloodTresh.setGeometry(QtCore.QRect(560, 260, 61, 20))
        self.L_LakeFloodTresh.setObjectName(_fromUtf8("L_LakeFloodTresh"))
        self.L_LakeOverFIFlow = QtGui.QLineEdit(Dialog)
        self.L_LakeOverFIFlow.setGeometry(QtCore.QRect(560, 380, 61, 20))
        self.L_LakeOverFIFlow.setObjectName(_fromUtf8("L_LakeOverFIFlow"))
        self.label_154 = QtGui.QLabel(Dialog)
        self.label_154.setGeometry(QtCore.QRect(410, 230, 111, 16))
        self.label_154.setObjectName(_fromUtf8("label_154"))
        self.L_ResrDepth = QtGui.QLineEdit(Dialog)
        self.L_ResrDepth.setGeometry(QtCore.QRect(560, 440, 61, 20))
        self.L_ResrDepth.setObjectName(_fromUtf8("L_ResrDepth"))
        self.label_66 = QtGui.QLabel(Dialog)
        self.label_66.setGeometry(QtCore.QRect(210, 210, 61, 16))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.isL_Lake_H = QtGui.QLineEdit(Dialog)
        self.isL_Lake_H.setGeometry(QtCore.QRect(110, 240, 61, 20))
        self.isL_Lake_H.setObjectName(_fromUtf8("isL_Lake_H"))
        self.label_60 = QtGui.QLabel(Dialog)
        self.label_60.setGeometry(QtCore.QRect(20, 270, 61, 16))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.label_70 = QtGui.QLabel(Dialog)
        self.label_70.setGeometry(QtCore.QRect(210, 120, 61, 16))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_53 = QtGui.QLabel(Dialog)
        self.label_53.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.isL_Lake_I = QtGui.QLineEdit(Dialog)
        self.isL_Lake_I.setGeometry(QtCore.QRect(110, 270, 61, 20))
        self.isL_Lake_I.setObjectName(_fromUtf8("isL_Lake_I"))
        self.isL_HEPP_Active = QtGui.QLineEdit(Dialog)
        self.isL_HEPP_Active.setGeometry(QtCore.QRect(560, 20, 61, 20))
        self.isL_HEPP_Active.setObjectName(_fromUtf8("isL_HEPP_Active"))
        self.label_151 = QtGui.QLabel(Dialog)
        self.label_151.setGeometry(QtCore.QRect(410, 140, 121, 16))
        self.label_151.setObjectName(_fromUtf8("label_151"))
        self.isL_Lake_K = QtGui.QLineEdit(Dialog)
        self.isL_Lake_K.setGeometry(QtCore.QRect(280, 30, 61, 20))
        self.isL_Lake_K.setObjectName(_fromUtf8("isL_Lake_K"))
        self.isL_Lake_E = QtGui.QLineEdit(Dialog)
        self.isL_Lake_E.setGeometry(QtCore.QRect(110, 150, 61, 20))
        self.isL_Lake_E.setObjectName(_fromUtf8("isL_Lake_E"))
        self.isL_Lake_A = QtGui.QLineEdit(Dialog)
        self.isL_Lake_A.setGeometry(QtCore.QRect(110, 30, 61, 20))
        self.isL_Lake_A.setObjectName(_fromUtf8("isL_Lake_A"))
        self.L_LakeLevelFullHEPP = QtGui.QLineEdit(Dialog)
        self.L_LakeLevelFullHEPP.setGeometry(QtCore.QRect(560, 170, 61, 20))
        self.L_LakeLevelFullHEPP.setObjectName(_fromUtf8("L_LakeLevelFullHEPP"))
        self.label_150 = QtGui.QLabel(Dialog)
        self.label_150.setGeometry(QtCore.QRect(410, 110, 111, 16))
        self.label_150.setObjectName(_fromUtf8("label_150"))
        self.label_56 = QtGui.QLabel(Dialog)
        self.label_56.setGeometry(QtCore.QRect(20, 210, 71, 16))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_52 = QtGui.QLabel(Dialog)
        self.label_52.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.label_71 = QtGui.QLabel(Dialog)
        self.label_71.setGeometry(QtCore.QRect(210, 90, 61, 16))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.label_69 = QtGui.QLabel(Dialog)
        self.label_69.setGeometry(QtCore.QRect(210, 60, 51, 16))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.isL_Lake_B = QtGui.QLineEdit(Dialog)
        self.isL_Lake_B.setGeometry(QtCore.QRect(110, 60, 61, 20))
        self.isL_Lake_B.setObjectName(_fromUtf8("isL_Lake_B"))
        self.isL_Lake_D = QtGui.QLineEdit(Dialog)
        self.isL_Lake_D.setGeometry(QtCore.QRect(110, 120, 61, 20))
        self.isL_Lake_D.setObjectName(_fromUtf8("isL_Lake_D"))
        self.isL_Lake_G = QtGui.QLineEdit(Dialog)
        self.isL_Lake_G.setGeometry(QtCore.QRect(110, 210, 61, 20))
        self.isL_Lake_G.setObjectName(_fromUtf8("isL_Lake_G"))
        self.isL_Lake_T = QtGui.QLineEdit(Dialog)
        self.isL_Lake_T.setGeometry(QtCore.QRect(280, 300, 61, 20))
        self.isL_Lake_T.setObjectName(_fromUtf8("isL_Lake_T"))
        self.isL_Lake_J = QtGui.QLineEdit(Dialog)
        self.isL_Lake_J.setGeometry(QtCore.QRect(110, 300, 61, 20))
        self.isL_Lake_J.setObjectName(_fromUtf8("isL_Lake_J"))
        self.label_54 = QtGui.QLabel(Dialog)
        self.label_54.setGeometry(QtCore.QRect(20, 120, 61, 16))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.L_LakeLevelHalfHEPP = QtGui.QLineEdit(Dialog)
        self.L_LakeLevelHalfHEPP.setGeometry(QtCore.QRect(560, 200, 61, 20))
        self.L_LakeLevelHalfHEPP.setObjectName(_fromUtf8("L_LakeLevelHalfHEPP"))
        self.L_LakeElevPreHEPP = QtGui.QLineEdit(Dialog)
        self.L_LakeElevPreHEPP.setGeometry(QtCore.QRect(560, 110, 61, 20))
        self.L_LakeElevPreHEPP.setObjectName(_fromUtf8("L_LakeElevPreHEPP"))
        self.label_62 = QtGui.QLabel(Dialog)
        self.label_62.setGeometry(QtCore.QRect(210, 30, 61, 16))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.label_68 = QtGui.QLabel(Dialog)
        self.label_68.setGeometry(QtCore.QRect(210, 150, 61, 16))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.L_LakeLevelNoHEPP = QtGui.QLineEdit(Dialog)
        self.L_LakeLevelNoHEPP.setGeometry(QtCore.QRect(560, 230, 61, 20))
        self.L_LakeLevelNoHEPP.setObjectName(_fromUtf8("L_LakeLevelNoHEPP"))
        self.label_55 = QtGui.QLabel(Dialog)
        self.label_55.setGeometry(QtCore.QRect(20, 90, 61, 16))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_159 = QtGui.QLabel(Dialog)
        self.label_159.setGeometry(QtCore.QRect(410, 380, 111, 16))
        self.label_159.setObjectName(_fromUtf8("label_159"))
        self.L_LakeOverFlowFract = QtGui.QLineEdit(Dialog)
        self.L_LakeOverFlowFract.setGeometry(QtCore.QRect(560, 350, 61, 20))
        self.L_LakeOverFlowFract.setObjectName(_fromUtf8("L_LakeOverFlowFract"))
        self.L_LakeBottomElev = QtGui.QLineEdit(Dialog)
        self.L_LakeBottomElev.setGeometry(QtCore.QRect(560, 80, 61, 20))
        self.L_LakeBottomElev.setObjectName(_fromUtf8("L_LakeBottomElev"))
        self.isL_Lake_P = QtGui.QLineEdit(Dialog)
        self.isL_Lake_P.setGeometry(QtCore.QRect(280, 180, 61, 20))
        self.isL_Lake_P.setObjectName(_fromUtf8("isL_Lake_P"))
        self.L_LakeOverFIPostHEPP = QtGui.QLineEdit(Dialog)
        self.L_LakeOverFIPostHEPP.setGeometry(QtCore.QRect(560, 140, 61, 20))
        self.L_LakeOverFIPostHEPP.setObjectName(_fromUtf8("L_LakeOverFIPostHEPP"))
        self.isL_Lake_R = QtGui.QLineEdit(Dialog)
        self.isL_Lake_R.setGeometry(QtCore.QRect(280, 240, 61, 20))
        self.isL_Lake_R.setObjectName(_fromUtf8("isL_Lake_R"))
        self.isL_Lake_L = QtGui.QLineEdit(Dialog)
        self.isL_Lake_L.setGeometry(QtCore.QRect(280, 60, 61, 20))
        self.isL_Lake_L.setObjectName(_fromUtf8("isL_Lake_L"))
        self.label_162 = QtGui.QLabel(Dialog)
        self.label_162.setGeometry(QtCore.QRect(410, 50, 111, 16))
        self.label_162.setObjectName(_fromUtf8("label_162"))
        self.isL_Lake_C = QtGui.QLineEdit(Dialog)
        self.isL_Lake_C.setGeometry(QtCore.QRect(110, 90, 61, 20))
        self.isL_Lake_C.setObjectName(_fromUtf8("isL_Lake_C"))
        self.label_156 = QtGui.QLabel(Dialog)
        self.label_156.setGeometry(QtCore.QRect(410, 290, 111, 16))
        self.label_156.setObjectName(_fromUtf8("label_156"))
        self.label_65 = QtGui.QLabel(Dialog)
        self.label_65.setGeometry(QtCore.QRect(210, 180, 61, 16))
        self.label_65.setObjectName(_fromUtf8("label_65"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Input Lake", None))
        self.isL_Lake_N.setText(_translate("Dialog", "0", None))
        self.L_LakeQmecsHEPP.setText(_translate("Dialog", "47.1", None))
        self.label_155.setText(_translate("Dialog", "L_LakeFloodTresh", None))
        self.isL_Lake_Q.setText(_translate("Dialog", "0", None))
        self.label_153.setText(_translate("Dialog", "L_LakeLevelHalfHEPP", None))
        self.label_157.setText(_translate("Dialog", "L_LakeQmecsSanFlow", None))
        self.isL_Lake_S.setText(_translate("Dialog", "0", None))
        self.label_152.setText(_translate("Dialog", "L_LakeLevelFullHEPP", None))
        self.label_67.setText(_translate("Dialog", "L_Lake?[S]", None))
        self.L_LakeTransMultiplier.setText(_translate("Dialog", "1", None))
        self.L_LakeQmecsSanFlow.setText(_translate("Dialog", "3", None))
        self.label_64.setText(_translate("Dialog", "L_Lake?[R]", None))
        self.label_72.setText(_translate("Dialog", "L_HEPP_Active?", None))
        self.isL_Lake_M.setText(_translate("Dialog", "0", None))
        self.label_160.setText(_translate("Dialog", "L_m3_per_kwh", None))
        self.label_57.setText(_translate("Dialog", "L_Lake?[F]", None))
        self.label_158.setText(_translate("Dialog", "L_LakeOverFlowFract", None))
        self.label_161.setText(_translate("Dialog", "L_ResrDepth", None))
        self.label_58.setText(_translate("Dialog", "L_Lake?[H]", None))
        self.isL_Lake_O.setText(_translate("Dialog", "0", None))
        self.L_m3_per_kwh.setText(_translate("Dialog", "1.584", None))
        self.isL_Lake_F.setText(_translate("Dialog", "0", None))
        self.label_63.setText(_translate("Dialog", "L_Lake?[T]", None))
        self.label_73.setText(_translate("Dialog", "L_LakeBottomElev", None))
        self.label_59.setText(_translate("Dialog", "L_Lake?[E]", None))
        self.label_61.setText(_translate("Dialog", "L_Lake?[J]", None))
        self.L_LakeFloodTresh.setText(_translate("Dialog", "363", None))
        self.L_LakeOverFIFlow.setText(_translate("Dialog", "4", None))
        self.label_154.setText(_translate("Dialog", "L_LakeLevelNoHEPP", None))
        self.L_ResrDepth.setText(_translate("Dialog", "10000", None))
        self.label_66.setText(_translate("Dialog", "L_Lake?[Q]", None))
        self.isL_Lake_H.setText(_translate("Dialog", "0", None))
        self.label_60.setText(_translate("Dialog", "L_Lake?[I]", None))
        self.label_70.setText(_translate("Dialog", "L_Lake?[N]", None))
        self.label_53.setText(_translate("Dialog", "L_Lake?B]", None))
        self.isL_Lake_I.setText(_translate("Dialog", "0", None))
        self.isL_HEPP_Active.setText(_translate("Dialog", "0", None))
        self.label_151.setText(_translate("Dialog", "L_LakeOverFIPostHEPP", None))
        self.isL_Lake_K.setText(_translate("Dialog", "0", None))
        self.isL_Lake_E.setText(_translate("Dialog", "0", None))
        self.isL_Lake_A.setText(_translate("Dialog", "0", None))
        self.L_LakeLevelFullHEPP.setText(_translate("Dialog", "362.3", None))
        self.label_150.setText(_translate("Dialog", "L_LakeElevPreHEPP", None))
        self.label_56.setText(_translate("Dialog", "L_Lake?[G]", None))
        self.label_52.setText(_translate("Dialog", "L_Lake?[A]", None))
        self.label_71.setText(_translate("Dialog", "L_Lake?[M]", None))
        self.label_69.setText(_translate("Dialog", "L_Lake?[L]", None))
        self.isL_Lake_B.setText(_translate("Dialog", "0", None))
        self.isL_Lake_D.setText(_translate("Dialog", "0", None))
        self.isL_Lake_G.setText(_translate("Dialog", "0", None))
        self.isL_Lake_T.setText(_translate("Dialog", "0", None))
        self.isL_Lake_J.setText(_translate("Dialog", "0", None))
        self.label_54.setText(_translate("Dialog", "L_Lake?[D]", None))
        self.L_LakeLevelHalfHEPP.setText(_translate("Dialog", "361.8", None))
        self.L_LakeElevPreHEPP.setText(_translate("Dialog", "362.3", None))
        self.label_62.setText(_translate("Dialog", "L_Lake?[K]", None))
        self.label_68.setText(_translate("Dialog", "L_Lake?[O]", None))
        self.L_LakeLevelNoHEPP.setText(_translate("Dialog", "359.5", None))
        self.label_55.setText(_translate("Dialog", "L_Lake?[C]", None))
        self.label_159.setText(_translate("Dialog", "L_LakeOverFIFlow", None))
        self.L_LakeOverFlowFract.setText(_translate("Dialog", "0.1", None))
        self.L_LakeBottomElev.setText(_translate("Dialog", "160", None))
        self.isL_Lake_P.setText(_translate("Dialog", "0", None))
        self.L_LakeOverFIPostHEPP.setText(_translate("Dialog", "362.6", None))
        self.isL_Lake_R.setText(_translate("Dialog", "0", None))
        self.isL_Lake_L.setText(_translate("Dialog", "0", None))
        self.label_162.setText(_translate("Dialog", "L_LakeTransMultiplier", None))
        self.isL_Lake_C.setText(_translate("Dialog", "0", None))
        self.label_156.setText(_translate("Dialog", "L_LakeQmecsHEPP", None))
        self.label_65.setText(_translate("Dialog", "L_Lake?[P]", None))

