# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_river.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(692, 387)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(340, 340, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.isDamThisStream_I = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_I.setGeometry(QtCore.QRect(450, 260, 31, 20))
        self.isDamThisStream_I.setObjectName(_fromUtf8("isDamThisStream_I"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(320, 50, 111, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.isDamThisStream_G = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_G.setGeometry(QtCore.QRect(450, 200, 31, 20))
        self.isDamThisStream_G.setObjectName(_fromUtf8("isDamThisStream_G"))
        self.isDamThisStream_B = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_B.setGeometry(QtCore.QRect(450, 50, 31, 20))
        self.isDamThisStream_B.setObjectName(_fromUtf8("isDamThisStream_B"))
        self.isDamThisStream_P = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_P.setGeometry(QtCore.QRect(650, 170, 31, 20))
        self.isDamThisStream_P.setObjectName(_fromUtf8("isDamThisStream_P"))
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(520, 260, 131, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_21 = QtGui.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(520, 110, 121, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.K_is_DamThisStreamlabel = QtGui.QLabel(Dialog)
        self.K_is_DamThisStreamlabel.setGeometry(QtCore.QRect(520, 20, 121, 16))
        self.K_is_DamThisStreamlabel.setObjectName(_fromUtf8("K_is_DamThisStreamlabel"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.isDamThisStream_S = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_S.setGeometry(QtCore.QRect(650, 260, 31, 20))
        self.isDamThisStream_S.setObjectName(_fromUtf8("isDamThisStream_S"))
        self.label_23 = QtGui.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(520, 140, 121, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.isDamThisStream_K = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_K.setGeometry(QtCore.QRect(650, 20, 31, 20))
        self.isDamThisStream_K.setObjectName(_fromUtf8("isDamThisStream_K"))
        self.isDamThisStream_A = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_A.setGeometry(QtCore.QRect(450, 20, 31, 20))
        self.isDamThisStream_A.setObjectName(_fromUtf8("isDamThisStream_A"))
        self.label_26 = QtGui.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(520, 290, 121, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(320, 200, 121, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.I_Tortuosity = QtGui.QLineEdit(Dialog)
        self.I_Tortuosity.setGeometry(QtCore.QRect(160, 50, 113, 20))
        self.I_Tortuosity.setObjectName(_fromUtf8("I_Tortuosity"))
        self.isDamThisStream_E = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_E.setGeometry(QtCore.QRect(450, 140, 31, 20))
        self.isDamThisStream_E.setObjectName(_fromUtf8("isDamThisStream_E"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(320, 20, 121, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(520, 50, 121, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.isDamThisStream_T = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_T.setGeometry(QtCore.QRect(650, 290, 31, 20))
        self.isDamThisStream_T.setObjectName(_fromUtf8("isDamThisStream_T"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(320, 110, 121, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(320, 80, 121, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_24 = QtGui.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(320, 290, 121, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.isDamThisStream_F = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_F.setGeometry(QtCore.QRect(450, 170, 31, 20))
        self.isDamThisStream_F.setObjectName(_fromUtf8("isDamThisStream_F"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(320, 230, 121, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_25 = QtGui.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(320, 260, 121, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.isDamThisStream_D = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_D.setGeometry(QtCore.QRect(450, 110, 31, 20))
        self.isDamThisStream_D.setObjectName(_fromUtf8("isDamThisStream_D"))
        self.isDamThisStream_M = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_M.setGeometry(QtCore.QRect(650, 80, 31, 20))
        self.isDamThisStream_M.setObjectName(_fromUtf8("isDamThisStream_M"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(320, 170, 121, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.isDamThisStream_C = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_C.setGeometry(QtCore.QRect(450, 80, 31, 20))
        self.isDamThisStream_C.setObjectName(_fromUtf8("isDamThisStream_C"))
        self.isDamThisStream_H = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_H.setGeometry(QtCore.QRect(450, 230, 31, 20))
        self.isDamThisStream_H.setObjectName(_fromUtf8("isDamThisStream_H"))
        self.label_19 = QtGui.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(520, 200, 121, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.isDamThisStream_O = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_O.setGeometry(QtCore.QRect(650, 140, 31, 20))
        self.isDamThisStream_O.setObjectName(_fromUtf8("isDamThisStream_O"))
        self.isDamThisStream_Q = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_Q.setGeometry(QtCore.QRect(650, 200, 31, 20))
        self.isDamThisStream_Q.setObjectName(_fromUtf8("isDamThisStream_Q"))
        self.label_22 = QtGui.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(520, 230, 121, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(320, 140, 121, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_20 = QtGui.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(520, 80, 121, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.isDamThisStream_J = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_J.setGeometry(QtCore.QRect(450, 290, 31, 20))
        self.isDamThisStream_J.setObjectName(_fromUtf8("isDamThisStream_J"))
        self.isDamThisStream_L = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_L.setGeometry(QtCore.QRect(650, 50, 31, 20))
        self.isDamThisStream_L.setObjectName(_fromUtf8("isDamThisStream_L"))
        self.isDamThisStream_R = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_R.setGeometry(QtCore.QRect(650, 230, 31, 20))
        self.isDamThisStream_R.setObjectName(_fromUtf8("isDamThisStream_R"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(520, 170, 121, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.I_RoutVelocm_per_s = QtGui.QLineEdit(Dialog)
        self.I_RoutVelocm_per_s.setGeometry(QtCore.QRect(160, 20, 113, 20))
        self.I_RoutVelocm_per_s.setObjectName(_fromUtf8("I_RoutVelocm_per_s"))
        self.isDamThisStream_N = QtGui.QLineEdit(Dialog)
        self.isDamThisStream_N.setGeometry(QtCore.QRect(650, 110, 31, 20))
        self.isDamThisStream_N.setObjectName(_fromUtf8("isDamThisStream_N"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 131, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.I_SurfLossFrac = QtGui.QLineEdit(Dialog)
        self.I_SurfLossFrac.setGeometry(QtCore.QRect(160, 110, 113, 20))
        self.I_SurfLossFrac.setObjectName(_fromUtf8("I_SurfLossFrac"))
        self.I_RiverflowDispersalFactor = QtGui.QLineEdit(Dialog)
        self.I_RiverflowDispersalFactor.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.I_RiverflowDispersalFactor.setObjectName(_fromUtf8("I_RiverflowDispersalFactor"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Input River Parameters", None))
        self.isDamThisStream_I.setText(_translate("Dialog", "0", None))
        self.label_9.setText(_translate("Dialog", "I_DaminThisStream?[B}", None))
        self.isDamThisStream_G.setText(_translate("Dialog", "0", None))
        self.isDamThisStream_B.setText(_translate("Dialog", "0", None))
        self.isDamThisStream_P.setText(_translate("Dialog", "0", None))
        self.label_18.setText(_translate("Dialog", "I_DaminThisStream?[S]", None))
        self.label_21.setText(_translate("Dialog", "I_DaminThisStream?[N]", None))
        self.K_is_DamThisStreamlabel.setText(_translate("Dialog", "I_DaminThisStream?[K]", None))
        self.label_2.setText(_translate("Dialog", "I_RoutVeloc_m_per_s", None))
        self.isDamThisStream_S.setText(_translate("Dialog", "0", None))
        self.label_23.setText(_translate("Dialog", "I_DaminThisStream?[O]", None))
        self.label_6.setText(_translate("Dialog", "I_RiverflowDispersalFactor", None))
        self.isDamThisStream_K.setText(_translate("Dialog", "0", None))
        self.isDamThisStream_A.setText(_translate("Dialog", "0", None))
        self.label_26.setText(_translate("Dialog", "I_DaminThisStream?[T]", None))
        self.label_14.setText(_translate("Dialog", "I_DaminThisStream?[G]", None))
        self.I_Tortuosity.setText(_translate("Dialog", "0.6", None))
        self.isDamThisStream_E.setText(_translate("Dialog", "0", None))
        self.label_8.setText(_translate("Dialog", "I_DaminThisStream?[A]", None))
        self.label_16.setText(_translate("Dialog", "I_DaminThisStream?[L]", None))
        self.isDamThisStream_T.setText(_translate("Dialog", "0", None))
        self.label_11.setText(_translate("Dialog", "I_DaminThisStream?[D]", None))
        self.label_10.setText(_translate("Dialog", "I_DaminThisStream?[C]", None))
        self.label_24.setText(_translate("Dialog", "I_DaminThisStream?[J]", None))
        self.label_3.setText(_translate("Dialog", "I_Tortuosity", None))
        self.isDamThisStream_F.setText(_translate("Dialog", "0", None))
        self.label_15.setText(_translate("Dialog", "I_DaminThisStream?[H]", None))
        self.label_25.setText(_translate("Dialog", "I_DaminThisStream?[I]", None))
        self.isDamThisStream_D.setText(_translate("Dialog", "0", None))
        self.isDamThisStream_M.setText(_translate("Dialog", "0", None))
        self.label_13.setText(_translate("Dialog", "I_DaminThisStream?[F]", None))
        self.isDamThisStream_C.setText(_translate("Dialog", "0", None))
        self.isDamThisStream_H.setText(_translate("Dialog", "0", None))
        self.label_19.setText(_translate("Dialog", "I_DaminThisStream?[Q]", None))
        self.isDamThisStream_O.setText(_translate("Dialog", "0", None))
        self.isDamThisStream_Q.setText(_translate("Dialog", "0", None))
        self.label_22.setText(_translate("Dialog", "I_DaminThisStream?[R]", None))
        self.label_12.setText(_translate("Dialog", "I_DaminThisStream?[E]", None))
        self.label_20.setText(_translate("Dialog", "I_DaminThisStream?[M]", None))
        self.isDamThisStream_J.setText(_translate("Dialog", "0", None))
        self.isDamThisStream_L.setText(_translate("Dialog", "0", None))
        self.isDamThisStream_R.setText(_translate("Dialog", "0", None))
        self.label_17.setText(_translate("Dialog", "I_DaminThisStream?[P]", None))
        self.I_RoutVelocm_per_s.setText(_translate("Dialog", "0.55", None))
        self.isDamThisStream_N.setText(_translate("Dialog", "0", None))
        self.label_7.setText(_translate("Dialog", "I_SurfLossFrac", None))
        self.I_SurfLossFrac.setText(_translate("Dialog", "0", None))
        self.I_RiverflowDispersalFactor.setText(_translate("Dialog", "0.6", None))

