# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_soil_and_plant_water.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(773, 374)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(410, 310, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label_174 = QtGui.QLabel(Dialog)
        self.label_174.setGeometry(QtCore.QRect(298, 50, 81, 16))
        self.label_174.setObjectName(_fromUtf8("label_174"))
        self.label_175 = QtGui.QLabel(Dialog)
        self.label_175.setGeometry(QtCore.QRect(318, 180, 121, 16))
        self.label_175.setObjectName(_fromUtf8("label_175"))
        self.label_176 = QtGui.QLabel(Dialog)
        self.label_176.setGeometry(QtCore.QRect(598, 250, 101, 16))
        self.label_176.setObjectName(_fromUtf8("label_176"))
        self.label_177 = QtGui.QLabel(Dialog)
        self.label_177.setGeometry(QtCore.QRect(48, 50, 81, 16))
        self.label_177.setObjectName(_fromUtf8("label_177"))
        self.I_InitRelSoil = QtGui.QLineEdit(Dialog)
        self.I_InitRelSoil.setGeometry(QtCore.QRect(700, 110, 51, 20))
        self.I_InitRelSoil.setObjectName(_fromUtf8("I_InitRelSoil"))
        self.I_PowerInfiltRed = QtGui.QLineEdit(Dialog)
        self.I_PowerInfiltRed.setGeometry(QtCore.QRect(180, 110, 71, 20))
        self.I_PowerInfiltRed.setObjectName(_fromUtf8("I_PowerInfiltRed"))
        self.label_178 = QtGui.QLabel(Dialog)
        self.label_178.setGeometry(QtCore.QRect(548, 110, 81, 16))
        self.label_178.setObjectName(_fromUtf8("label_178"))
        self.I_MaxInfSoil = QtGui.QLineEdit(Dialog)
        self.I_MaxInfSoil.setGeometry(QtCore.QRect(180, 80, 71, 20))
        self.I_MaxInfSoil.setObjectName(_fromUtf8("I_MaxInfSoil"))
        self.I_MaxInf = QtGui.QLineEdit(Dialog)
        self.I_MaxInf.setGeometry(QtCore.QRect(180, 50, 71, 20))
        self.I_MaxInf.setObjectName(_fromUtf8("I_MaxInf"))
        self.I_InitRelGW = QtGui.QLineEdit(Dialog)
        self.I_InitRelGW.setGeometry(QtCore.QRect(450, 50, 51, 20))
        self.I_InitRelGW.setObjectName(_fromUtf8("I_InitRelGW"))
        self.I_RainMaxIntDripDur = QtGui.QLineEdit(Dialog)
        self.I_RainMaxIntDripDur.setGeometry(QtCore.QRect(450, 270, 51, 20))
        self.I_RainMaxIntDripDur.setObjectName(_fromUtf8("I_RainMaxIntDripDur"))
        self.label_179 = QtGui.QLabel(Dialog)
        self.label_179.setGeometry(QtCore.QRect(28, 270, 121, 16))
        self.label_179.setObjectName(_fromUtf8("label_179"))
        self.I_AvailQaterClassConst = QtGui.QLineEdit(Dialog)
        self.I_AvailQaterClassConst.setGeometry(QtCore.QRect(180, 240, 71, 20))
        self.I_AvailQaterClassConst.setObjectName(_fromUtf8("I_AvailQaterClassConst"))
        self.label_180 = QtGui.QLabel(Dialog)
        self.label_180.setGeometry(QtCore.QRect(298, 110, 101, 16))
        self.label_180.setObjectName(_fromUtf8("label_180"))
        self.I_SoilSatMinFCConst = QtGui.QLineEdit(Dialog)
        self.I_SoilSatMinFCConst.setGeometry(QtCore.QRect(180, 270, 71, 20))
        self.I_SoilSatMinFCConst.setObjectName(_fromUtf8("I_SoilSatMinFCConst"))
        self.label_181 = QtGui.QLabel(Dialog)
        self.label_181.setGeometry(QtCore.QRect(338, 20, 121, 16))
        self.label_181.setObjectName(_fromUtf8("label_181"))
        self.isI_SoilPropConst = QtGui.QLineEdit(Dialog)
        self.isI_SoilPropConst.setGeometry(QtCore.QRect(180, 210, 71, 20))
        self.isI_SoilPropConst.setObjectName(_fromUtf8("isI_SoilPropConst"))
        self.label_182 = QtGui.QLabel(Dialog)
        self.label_182.setGeometry(QtCore.QRect(108, 20, 121, 16))
        self.label_182.setObjectName(_fromUtf8("label_182"))
        self.label_183 = QtGui.QLabel(Dialog)
        self.label_183.setGeometry(QtCore.QRect(298, 140, 101, 16))
        self.label_183.setObjectName(_fromUtf8("label_183"))
        self.label_184 = QtGui.QLabel(Dialog)
        self.label_184.setGeometry(QtCore.QRect(608, 20, 81, 16))
        self.label_184.setObjectName(_fromUtf8("label_184"))
        self.label_185 = QtGui.QLabel(Dialog)
        self.label_185.setGeometry(QtCore.QRect(548, 270, 91, 16))
        self.label_185.setObjectName(_fromUtf8("label_185"))
        self.I_PercFracMultiplier = QtGui.QLineEdit(Dialog)
        self.I_PercFracMultiplier.setGeometry(QtCore.QRect(700, 50, 51, 20))
        self.I_PercFracMultiplier.setObjectName(_fromUtf8("I_PercFracMultiplier"))
        self.label_186 = QtGui.QLabel(Dialog)
        self.label_186.setGeometry(QtCore.QRect(48, 80, 81, 16))
        self.label_186.setObjectName(_fromUtf8("label_186"))
        self.I_SoilQflowFract = QtGui.QLineEdit(Dialog)
        self.I_SoilQflowFract.setGeometry(QtCore.QRect(700, 270, 51, 20))
        self.I_SoilQflowFract.setObjectName(_fromUtf8("I_SoilQflowFract"))
        self.label_187 = QtGui.QLabel(Dialog)
        self.label_187.setGeometry(QtCore.QRect(28, 210, 81, 16))
        self.label_187.setObjectName(_fromUtf8("label_187"))
        self.label_188 = QtGui.QLabel(Dialog)
        self.label_188.setGeometry(QtCore.QRect(28, 240, 121, 16))
        self.label_188.setObjectName(_fromUtf8("label_188"))
        self.label_189 = QtGui.QLabel(Dialog)
        self.label_189.setGeometry(QtCore.QRect(608, 90, 81, 16))
        self.label_189.setObjectName(_fromUtf8("label_189"))
        self.label_190 = QtGui.QLabel(Dialog)
        self.label_190.setGeometry(QtCore.QRect(298, 210, 131, 16))
        self.label_190.setObjectName(_fromUtf8("label_190"))
        self.label_191 = QtGui.QLabel(Dialog)
        self.label_191.setGeometry(QtCore.QRect(548, 50, 111, 16))
        self.label_191.setObjectName(_fromUtf8("label_191"))
        self.isI_GWRelFracConst = QtGui.QLineEdit(Dialog)
        self.isI_GWRelFracConst.setGeometry(QtCore.QRect(450, 80, 51, 20))
        self.isI_GWRelFracConst.setObjectName(_fromUtf8("isI_GWRelFracConst"))
        self.label_192 = QtGui.QLabel(Dialog)
        self.label_192.setGeometry(QtCore.QRect(298, 240, 111, 16))
        self.label_192.setObjectName(_fromUtf8("label_192"))
        self.label_193 = QtGui.QLabel(Dialog)
        self.label_193.setGeometry(QtCore.QRect(48, 110, 81, 16))
        self.label_193.setObjectName(_fromUtf8("label_193"))
        self.I_GWRelFracConst = QtGui.QLineEdit(Dialog)
        self.I_GWRelFracConst.setGeometry(QtCore.QRect(450, 140, 51, 20))
        self.I_GWRelFracConst.setObjectName(_fromUtf8("I_GWRelFracConst"))
        self.I_IntercepEffectionTransp = QtGui.QLineEdit(Dialog)
        self.I_IntercepEffectionTransp.setGeometry(QtCore.QRect(450, 210, 51, 20))
        self.I_IntercepEffectionTransp.setObjectName(_fromUtf8("I_IntercepEffectionTransp"))
        self.label_194 = QtGui.QLabel(Dialog)
        self.label_194.setGeometry(QtCore.QRect(548, 210, 111, 16))
        self.label_194.setObjectName(_fromUtf8("label_194"))
        self.label_195 = QtGui.QLabel(Dialog)
        self.label_195.setGeometry(QtCore.QRect(98, 180, 151, 16))
        self.label_195.setObjectName(_fromUtf8("label_195"))
        self.I_RainIntercDripRt = QtGui.QLineEdit(Dialog)
        self.I_RainIntercDripRt.setGeometry(QtCore.QRect(450, 240, 51, 20))
        self.I_RainIntercDripRt.setObjectName(_fromUtf8("I_RainIntercDripRt"))
        self.I_EvapotransMethod = QtGui.QLineEdit(Dialog)
        self.I_EvapotransMethod.setGeometry(QtCore.QRect(700, 210, 51, 20))
        self.I_EvapotransMethod.setObjectName(_fromUtf8("I_EvapotransMethod"))
        self.label_196 = QtGui.QLabel(Dialog)
        self.label_196.setGeometry(QtCore.QRect(298, 80, 101, 16))
        self.label_196.setObjectName(_fromUtf8("label_196"))
        self.label_197 = QtGui.QLabel(Dialog)
        self.label_197.setGeometry(QtCore.QRect(298, 270, 111, 16))
        self.label_197.setObjectName(_fromUtf8("label_197"))
        self.label_198 = QtGui.QLabel(Dialog)
        self.label_198.setGeometry(QtCore.QRect(598, 180, 101, 16))
        self.label_198.setObjectName(_fromUtf8("label_198"))
        self.I_MaxDynGWConst = QtGui.QLineEdit(Dialog)
        self.I_MaxDynGWConst.setGeometry(QtCore.QRect(450, 110, 51, 20))
        self.I_MaxDynGWConst.setObjectName(_fromUtf8("I_MaxDynGWConst"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Input Soil and Plant Water", None))
        self.label_174.setText(_translate("Dialog", "I_InitRelGW", None))
        self.label_175.setText(_translate("Dialog", "Rainfall Interception, mm", None))
        self.label_176.setText(_translate("Dialog", "Soil Quick Flow", None))
        self.label_177.setText(_translate("Dialog", "I_MaxInf", None))
        self.I_InitRelSoil.setText(_translate("Dialog", "1", None))
        self.I_PowerInfiltRed.setText(_translate("Dialog", "3.5", None))
        self.label_178.setText(_translate("Dialog", "I_InitRelSoil", None))
        self.I_MaxInfSoil.setText(_translate("Dialog", "200", None))
        self.I_MaxInf.setText(_translate("Dialog", "700", None))
        self.I_InitRelGW.setText(_translate("Dialog", "1", None))
        self.I_RainMaxIntDripDur.setText(_translate("Dialog", "0.5", None))
        self.label_179.setText(_translate("Dialog", "I_SoilSatMinFCConst", None))
        self.I_AvailQaterClassConst.setText(_translate("Dialog", "300", None))
        self.label_180.setText(_translate("Dialog", "I_MaxDynGWConst", None))
        self.I_SoilSatMinFCConst.setText(_translate("Dialog", "100", None))
        self.label_181.setText(_translate("Dialog", "Ground Water, mm", None))
        self.isI_SoilPropConst.setText(_translate("Dialog", "0", None))
        self.label_182.setText(_translate("Dialog", "Infitration, mm day-1", None))
        self.label_183.setText(_translate("Dialog", "I_GWRelFracConst", None))
        self.label_184.setText(_translate("Dialog", "Percolation", None))
        self.label_185.setText(_translate("Dialog", "I_SoilQflowFract", None))
        self.I_PercFracMultiplier.setText(_translate("Dialog", "0.05", None))
        self.label_186.setText(_translate("Dialog", "I_MaxInfSoil", None))
        self.I_SoilQflowFract.setText(_translate("Dialog", "0.1", None))
        self.label_187.setText(_translate("Dialog", "I_SoilPropConst?", None))
        self.label_188.setText(_translate("Dialog", "I_AvailWaterClassConst", None))
        self.label_189.setText(_translate("Dialog", "Initial Soil Water", None))
        self.label_190.setText(_translate("Dialog", "I_IntercepEffectionTransp", None))
        self.label_191.setText(_translate("Dialog", "I_PercFracMultiplier", None))
        self.isI_GWRelFracConst.setText(_translate("Dialog", "0", None))
        self.label_192.setText(_translate("Dialog", "I_RainIntercDripRt", None))
        self.label_193.setText(_translate("Dialog", "I_PowerInfiltRed", None))
        self.I_GWRelFracConst.setText(_translate("Dialog", "0.01", None))
        self.I_IntercepEffectionTransp.setText(_translate("Dialog", "0.1", None))
        self.label_194.setText(_translate("Dialog", "I_EvapotransMethod", None))
        self.label_195.setText(_translate("Dialog", "Water Available for Plant, mm", None))
        self.I_RainIntercDripRt.setText(_translate("Dialog", "10", None))
        self.I_EvapotransMethod.setText(_translate("Dialog", "1", None))
        self.label_196.setText(_translate("Dialog", "I_GWRelFracConst?", None))
        self.label_197.setText(_translate("Dialog", "I_RainMaxIntDripDur", None))
        self.label_198.setText(_translate("Dialog", "Evapotranspiration", None))
        self.I_MaxDynGWConst.setText(_translate("Dialog", "100", None))

