# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_lake_hepp.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(537, 419)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/background/GenRiver logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(180, 380, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label_143 = QtGui.QLabel(Dialog)
        self.label_143.setGeometry(QtCore.QRect(310, 200, 161, 16))
        self.label_143.setObjectName(_fromUtf8("label_143"))
        self.O_CumRivInflowtoLakeMP_2 = QtGui.QLineEdit(Dialog)
        self.O_CumRivInflowtoLakeMP_2.setGeometry(QtCore.QRect(202, 60, 41, 20))
        self.O_CumRivInflowtoLakeMP_2.setObjectName(_fromUtf8("O_CumRivInflowtoLakeMP_2"))
        self.O_CumRivOutFlowMP_1 = QtGui.QLineEdit(Dialog)
        self.O_CumRivOutFlowMP_1.setGeometry(QtCore.QRect(202, 140, 41, 20))
        self.O_CumRivOutFlowMP_1.setObjectName(_fromUtf8("O_CumRivOutFlowMP_1"))
        self.O_FrSurfQuickflow = QtGui.QLineEdit(Dialog)
        self.O_FrSurfQuickflow.setGeometry(QtCore.QRect(202, 310, 41, 20))
        self.O_FrSurfQuickflow.setObjectName(_fromUtf8("O_FrSurfQuickflow"))
        self.label_148 = QtGui.QLabel(Dialog)
        self.label_148.setGeometry(QtCore.QRect(310, 280, 161, 16))
        self.label_148.setObjectName(_fromUtf8("label_148"))
        self.label_140 = QtGui.QLabel(Dialog)
        self.label_140.setGeometry(QtCore.QRect(310, 90, 161, 16))
        self.label_140.setObjectName(_fromUtf8("label_140"))
        self.label_133 = QtGui.QLabel(Dialog)
        self.label_133.setGeometry(QtCore.QRect(30, 60, 161, 16))
        self.label_133.setObjectName(_fromUtf8("label_133"))
        self.label_136 = QtGui.QLabel(Dialog)
        self.label_136.setGeometry(QtCore.QRect(30, 170, 161, 16))
        self.label_136.setObjectName(_fromUtf8("label_136"))
        self.O_FrSoilQuickFlow = QtGui.QLineEdit(Dialog)
        self.O_FrSoilQuickFlow.setGeometry(QtCore.QRect(202, 280, 41, 20))
        self.O_FrSoilQuickFlow.setObjectName(_fromUtf8("O_FrSoilQuickFlow"))
        self.O_FrBaseFlow = QtGui.QLineEdit(Dialog)
        self.O_FrBaseFlow.setGeometry(QtCore.QRect(202, 250, 41, 20))
        self.O_FrBaseFlow.setObjectName(_fromUtf8("O_FrBaseFlow"))
        self.O_HEPP_Kwh_per_dayMP_2 = QtGui.QLineEdit(Dialog)
        self.O_HEPP_Kwh_per_dayMP_2.setGeometry(QtCore.QRect(482, 60, 41, 20))
        self.O_HEPP_Kwh_per_dayMP_2.setObjectName(_fromUtf8("O_HEPP_Kwh_per_dayMP_2"))
        self.label_142 = QtGui.QLabel(Dialog)
        self.label_142.setGeometry(QtCore.QRect(310, 170, 161, 16))
        self.label_142.setObjectName(_fromUtf8("label_142"))
        self.label_132 = QtGui.QLabel(Dialog)
        self.label_132.setGeometry(QtCore.QRect(30, 30, 161, 16))
        self.label_132.setObjectName(_fromUtf8("label_132"))
        self.O_HEPP_Kwh_per_dayMP_3 = QtGui.QLineEdit(Dialog)
        self.O_HEPP_Kwh_per_dayMP_3.setGeometry(QtCore.QRect(482, 90, 41, 20))
        self.O_HEPP_Kwh_per_dayMP_3.setObjectName(_fromUtf8("O_HEPP_Kwh_per_dayMP_3"))
        self.label_145 = QtGui.QLabel(Dialog)
        self.label_145.setGeometry(QtCore.QRect(30, 280, 161, 16))
        self.label_145.setObjectName(_fromUtf8("label_145"))
        self.label_139 = QtGui.QLabel(Dialog)
        self.label_139.setGeometry(QtCore.QRect(310, 60, 151, 16))
        self.label_139.setObjectName(_fromUtf8("label_139"))
        self.label_146 = QtGui.QLabel(Dialog)
        self.label_146.setGeometry(QtCore.QRect(30, 310, 161, 16))
        self.label_146.setObjectName(_fromUtf8("label_146"))
        self.label_141 = QtGui.QLabel(Dialog)
        self.label_141.setGeometry(QtCore.QRect(310, 140, 161, 16))
        self.label_141.setObjectName(_fromUtf8("label_141"))
        self.O_CumHEPPOutFlowMP_1 = QtGui.QLineEdit(Dialog)
        self.O_CumHEPPOutFlowMP_1.setGeometry(QtCore.QRect(482, 140, 41, 20))
        self.O_CumHEPPOutFlowMP_1.setObjectName(_fromUtf8("O_CumHEPPOutFlowMP_1"))
        self.label_135 = QtGui.QLabel(Dialog)
        self.label_135.setGeometry(QtCore.QRect(30, 140, 161, 16))
        self.label_135.setObjectName(_fromUtf8("label_135"))
        self.label_147 = QtGui.QLabel(Dialog)
        self.label_147.setGeometry(QtCore.QRect(310, 250, 161, 16))
        self.label_147.setObjectName(_fromUtf8("label_147"))
        self.O_CumRivOutFlowMP_3 = QtGui.QLineEdit(Dialog)
        self.O_CumRivOutFlowMP_3.setGeometry(QtCore.QRect(202, 200, 41, 20))
        self.O_CumRivOutFlowMP_3.setObjectName(_fromUtf8("O_CumRivOutFlowMP_3"))
        self.O_CumHEPPOutFlowMP_2 = QtGui.QLineEdit(Dialog)
        self.O_CumHEPPOutFlowMP_2.setGeometry(QtCore.QRect(482, 170, 41, 20))
        self.O_CumHEPPOutFlowMP_2.setObjectName(_fromUtf8("O_CumHEPPOutFlowMP_2"))
        self.O_RelOPTimeHEPPMP_1 = QtGui.QLineEdit(Dialog)
        self.O_RelOPTimeHEPPMP_1.setGeometry(QtCore.QRect(482, 250, 41, 20))
        self.O_RelOPTimeHEPPMP_1.setObjectName(_fromUtf8("O_RelOPTimeHEPPMP_1"))
        self.O_CumRivInflowtoLakeMP_1 = QtGui.QLineEdit(Dialog)
        self.O_CumRivInflowtoLakeMP_1.setGeometry(QtCore.QRect(202, 30, 41, 20))
        self.O_CumRivInflowtoLakeMP_1.setObjectName(_fromUtf8("O_CumRivInflowtoLakeMP_1"))
        self.O_RelOPTimeHEPPMP_3 = QtGui.QLineEdit(Dialog)
        self.O_RelOPTimeHEPPMP_3.setGeometry(QtCore.QRect(482, 310, 41, 20))
        self.O_RelOPTimeHEPPMP_3.setObjectName(_fromUtf8("O_RelOPTimeHEPPMP_3"))
        self.O_CumRivInflowtoLakeMP_3 = QtGui.QLineEdit(Dialog)
        self.O_CumRivInflowtoLakeMP_3.setGeometry(QtCore.QRect(202, 90, 41, 20))
        self.O_CumRivInflowtoLakeMP_3.setObjectName(_fromUtf8("O_CumRivInflowtoLakeMP_3"))
        self.O_HEPP_Kwh_per_dayMP_1 = QtGui.QLineEdit(Dialog)
        self.O_HEPP_Kwh_per_dayMP_1.setGeometry(QtCore.QRect(482, 30, 41, 20))
        self.O_HEPP_Kwh_per_dayMP_1.setObjectName(_fromUtf8("O_HEPP_Kwh_per_dayMP_1"))
        self.label_138 = QtGui.QLabel(Dialog)
        self.label_138.setGeometry(QtCore.QRect(310, 30, 161, 16))
        self.label_138.setObjectName(_fromUtf8("label_138"))
        self.O_CumHEPPOutFlowMP_3 = QtGui.QLineEdit(Dialog)
        self.O_CumHEPPOutFlowMP_3.setGeometry(QtCore.QRect(482, 200, 41, 20))
        self.O_CumHEPPOutFlowMP_3.setObjectName(_fromUtf8("O_CumHEPPOutFlowMP_3"))
        self.label_134 = QtGui.QLabel(Dialog)
        self.label_134.setGeometry(QtCore.QRect(30, 90, 161, 16))
        self.label_134.setObjectName(_fromUtf8("label_134"))
        self.label_144 = QtGui.QLabel(Dialog)
        self.label_144.setGeometry(QtCore.QRect(30, 250, 161, 16))
        self.label_144.setObjectName(_fromUtf8("label_144"))
        self.label_137 = QtGui.QLabel(Dialog)
        self.label_137.setGeometry(QtCore.QRect(30, 200, 161, 16))
        self.label_137.setObjectName(_fromUtf8("label_137"))
        self.O_CumRivOutFlowMP_2 = QtGui.QLineEdit(Dialog)
        self.O_CumRivOutFlowMP_2.setGeometry(QtCore.QRect(202, 170, 41, 20))
        self.O_CumRivOutFlowMP_2.setObjectName(_fromUtf8("O_CumRivOutFlowMP_2"))
        self.O_RelOPTimeHEPPMP_2 = QtGui.QLineEdit(Dialog)
        self.O_RelOPTimeHEPPMP_2.setGeometry(QtCore.QRect(482, 280, 41, 20))
        self.O_RelOPTimeHEPPMP_2.setObjectName(_fromUtf8("O_RelOPTimeHEPPMP_2"))
        self.label_149 = QtGui.QLabel(Dialog)
        self.label_149.setGeometry(QtCore.QRect(310, 310, 161, 16))
        self.label_149.setObjectName(_fromUtf8("label_149"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Input Lake HEPP", None))
        self.label_143.setText(_translate("Dialog", "O_CumHEPPOutFlowMP[3]", None))
        self.O_CumRivInflowtoLakeMP_2.setText(_translate("Dialog", "0", None))
        self.O_CumRivOutFlowMP_1.setText(_translate("Dialog", "0", None))
        self.O_FrSurfQuickflow.setText(_translate("Dialog", "0", None))
        self.label_148.setText(_translate("Dialog", "O_RelOPTimeHEPPMP[2]", None))
        self.label_140.setText(_translate("Dialog", "O_HEPP_Kwh_per_dayMP[3]", None))
        self.label_133.setText(_translate("Dialog", "O_CumRivInflowtoLakeMP[2]", None))
        self.label_136.setText(_translate("Dialog", "O_CumRivOutFlowMP[2]", None))
        self.O_FrSoilQuickFlow.setText(_translate("Dialog", "0", None))
        self.O_FrBaseFlow.setText(_translate("Dialog", "0", None))
        self.O_HEPP_Kwh_per_dayMP_2.setText(_translate("Dialog", "0", None))
        self.label_142.setText(_translate("Dialog", "O_CumHEPPOutFlowMP[2]", None))
        self.label_132.setText(_translate("Dialog", "O_CumRivInflowtoLakeMP[1]", None))
        self.O_HEPP_Kwh_per_dayMP_3.setText(_translate("Dialog", "0", None))
        self.label_145.setText(_translate("Dialog", "O_FrSoilQuickFlow", None))
        self.label_139.setText(_translate("Dialog", "O_HEPP_Kwh_per_dayMP[2]", None))
        self.label_146.setText(_translate("Dialog", "O_FrSurfQuickFlow", None))
        self.label_141.setText(_translate("Dialog", "O_CumHEPPOutFlowMP[1]", None))
        self.O_CumHEPPOutFlowMP_1.setText(_translate("Dialog", "0", None))
        self.label_135.setText(_translate("Dialog", "O_CumRivOutFlowMP[1]", None))
        self.label_147.setText(_translate("Dialog", "O_RelOPTimeHEPPMP[1]", None))
        self.O_CumRivOutFlowMP_3.setText(_translate("Dialog", "0", None))
        self.O_CumHEPPOutFlowMP_2.setText(_translate("Dialog", "0", None))
        self.O_RelOPTimeHEPPMP_1.setText(_translate("Dialog", "0", None))
        self.O_CumRivInflowtoLakeMP_1.setText(_translate("Dialog", "0", None))
        self.O_RelOPTimeHEPPMP_3.setText(_translate("Dialog", "0", None))
        self.O_CumRivInflowtoLakeMP_3.setText(_translate("Dialog", "0", None))
        self.O_HEPP_Kwh_per_dayMP_1.setText(_translate("Dialog", "0", None))
        self.label_138.setText(_translate("Dialog", "O_HEPP_Kwh_per_dayMP[1]", None))
        self.O_CumHEPPOutFlowMP_3.setText(_translate("Dialog", "0", None))
        self.label_134.setText(_translate("Dialog", "O_CumRivInflowtoLakeMP[3]", None))
        self.label_144.setText(_translate("Dialog", "O_FrBaseFlow", None))
        self.label_137.setText(_translate("Dialog", "O_CumRivOutFlowMP[3]", None))
        self.O_CumRivOutFlowMP_2.setText(_translate("Dialog", "0", None))
        self.O_RelOPTimeHEPPMP_2.setText(_translate("Dialog", "0", None))
        self.label_149.setText(_translate("Dialog", "O_RelOPTimeHEPPMP[3]", None))

import images_rc
