# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'output_timeseries.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(825, 573)
        self.label_168 = QtGui.QLabel(Dialog)
        self.label_168.setGeometry(QtCore.QRect(10, 10, 93, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_168.sizePolicy().hasHeightForWidth())
        self.label_168.setSizePolicy(sizePolicy)
        self.label_168.setMaximumSize(QtCore.QSize(200, 100))
        self.label_168.setObjectName(_fromUtf8("label_168"))
        self.yearProgress = QtGui.QLCDNumber(Dialog)
        self.yearProgress.setGeometry(QtCore.QRect(150, 40, 64, 23))
        self.yearProgress.setMaximumSize(QtCore.QSize(100, 50))
        self.yearProgress.setObjectName(_fromUtf8("yearProgress"))
        self.label_169 = QtGui.QLabel(Dialog)
        self.label_169.setGeometry(QtCore.QRect(10, 40, 19, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_169.sizePolicy().hasHeightForWidth())
        self.label_169.setSizePolicy(sizePolicy)
        self.label_169.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_169.setObjectName(_fromUtf8("label_169"))
        self.label_170 = QtGui.QLabel(Dialog)
        self.label_170.setGeometry(QtCore.QRect(120, 40, 21, 16))
        self.label_170.setMaximumSize(QtCore.QSize(200, 50))
        self.label_170.setObjectName(_fromUtf8("label_170"))
        self.dayProgress = QtGui.QLCDNumber(Dialog)
        self.dayProgress.setGeometry(QtCore.QRect(40, 40, 64, 23))
        self.dayProgress.setMaximumSize(QtCore.QSize(100, 50))
        self.dayProgress.setObjectName(_fromUtf8("dayProgress"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(260, 40, 551, 481))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 201, 71))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 201, 141))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 20, 201, 141))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 250, 201, 141))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_32 = QtGui.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.groupBox_5)
        self.label_35.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.groupBox_5)
        self.label_36.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(340, 170, 201, 141))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_37 = QtGui.QLabel(self.groupBox_6)
        self.label_37.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.groupBox_6)
        self.label_40.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setGeometry(QtCore.QRect(340, 330, 201, 141))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_42 = QtGui.QLabel(self.groupBox_7)
        self.label_42.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_43 = QtGui.QLabel(self.groupBox_7)
        self.label_43.setGeometry(QtCore.QRect(10, 50, 151, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_44 = QtGui.QLabel(self.groupBox_7)
        self.label_44.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.groupBox_7)
        self.label_45.setGeometry(QtCore.QRect(10, 70, 151, 16))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.groupBox_7)
        self.label_46.setGeometry(QtCore.QRect(10, 110, 91, 16))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.page1Display = QtGui.QPushButton(Dialog)
        self.page1Display.setGeometry(QtCore.QRect(130, 80, 75, 23))
        self.page1Display.setObjectName(_fromUtf8("page1Display"))
        self.label_47 = QtGui.QLabel(Dialog)
        self.label_47.setGeometry(QtCore.QRect(30, 80, 46, 13))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.page2Display = QtGui.QPushButton(Dialog)
        self.page2Display.setGeometry(QtCore.QRect(130, 130, 75, 23))
        self.page2Display.setObjectName(_fromUtf8("page2Display"))
        self.label_48 = QtGui.QLabel(Dialog)
        self.label_48.setGeometry(QtCore.QRect(30, 130, 46, 13))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.page3Display = QtGui.QPushButton(Dialog)
        self.page3Display.setGeometry(QtCore.QRect(130, 190, 75, 23))
        self.page3Display.setObjectName(_fromUtf8("page3Display"))
        self.label_49 = QtGui.QLabel(Dialog)
        self.label_49.setGeometry(QtCore.QRect(30, 190, 46, 13))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.page4Display = QtGui.QPushButton(Dialog)
        self.page4Display.setGeometry(QtCore.QRect(130, 250, 75, 23))
        self.page4Display.setObjectName(_fromUtf8("page4Display"))
        self.label_50 = QtGui.QLabel(Dialog)
        self.label_50.setGeometry(QtCore.QRect(30, 250, 46, 13))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.page5Display = QtGui.QPushButton(Dialog)
        self.page5Display.setGeometry(QtCore.QRect(130, 310, 75, 23))
        self.page5Display.setObjectName(_fromUtf8("page5Display"))
        self.label_51 = QtGui.QLabel(Dialog)
        self.label_51.setGeometry(QtCore.QRect(30, 310, 46, 13))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.page6Display = QtGui.QPushButton(Dialog)
        self.page6Display.setGeometry(QtCore.QRect(130, 370, 75, 23))
        self.page6Display.setObjectName(_fromUtf8("page6Display"))
        self.label_52 = QtGui.QLabel(Dialog)
        self.label_52.setGeometry(QtCore.QRect(30, 370, 46, 13))
        self.label_52.setObjectName(_fromUtf8("label_52"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Output Timeseries", None))
        self.label_168.setText(_translate("Dialog", "Simulation progress", None))
        self.label_169.setText(_translate("Dialog", "Day", None))
        self.label_170.setText(_translate("Dialog", "Year", None))
        self.groupBox.setTitle(_translate("Dialog", "Water Balance", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Page 1", None))
        self.label.setText(_translate("Dialog", "I_RFlowdata_mmday", None))
        self.label_2.setText(_translate("Dialog", "L_InFlowtoLake", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Page 2", None))
        self.label_7.setText(_translate("Dialog", "O_RainAcc", None))
        self.label_8.setText(_translate("Dialog", "O_IntercAcc", None))
        self.label_9.setText(_translate("Dialog", "O_SurfQFlowAcc", None))
        self.label_10.setText(_translate("Dialog", "O_EvapoTransAcc", None))
        self.label_11.setText(_translate("Dialog", "O_InfAcc", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Page 3", None))
        self.label_17.setText(_translate("Dialog", "O_RainAcc", None))
        self.label_18.setText(_translate("Dialog", "O_IntercAcc", None))
        self.label_19.setText(_translate("Dialog", "O_SurfQFlowAcc", None))
        self.label_20.setText(_translate("Dialog", "O_EvapoTransAcc", None))
        self.label_21.setText(_translate("Dialog", "O_InfAcc", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Page 4", None))
        self.label_32.setText(_translate("Dialog", "O_RainAcc", None))
        self.label_33.setText(_translate("Dialog", "O_IntercAcc", None))
        self.label_34.setText(_translate("Dialog", "O_SurfQFlowAcc", None))
        self.label_35.setText(_translate("Dialog", "O_EvapoTransAcc", None))
        self.label_36.setText(_translate("Dialog", "O_InfAcc", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Page 5", None))
        self.label_37.setText(_translate("Dialog", "O_RainAcc", None))
        self.label_38.setText(_translate("Dialog", "O_IntercAcc", None))
        self.label_39.setText(_translate("Dialog", "O_SurfQFlowAcc", None))
        self.label_40.setText(_translate("Dialog", "O_EvapoTransAcc", None))
        self.label_41.setText(_translate("Dialog", "O_InfAcc", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Page 6", None))
        self.label_42.setText(_translate("Dialog", "O_RainAcc", None))
        self.label_43.setText(_translate("Dialog", "O_IntercAcc", None))
        self.label_44.setText(_translate("Dialog", "O_SurfQFlowAcc", None))
        self.label_45.setText(_translate("Dialog", "O_EvapoTransAcc", None))
        self.label_46.setText(_translate("Dialog", "O_InfAcc", None))
        self.page1Display.setText(_translate("Dialog", "Display", None))
        self.label_47.setText(_translate("Dialog", "Page 1", None))
        self.page2Display.setText(_translate("Dialog", "Display", None))
        self.label_48.setText(_translate("Dialog", "Page 2", None))
        self.page3Display.setText(_translate("Dialog", "Display", None))
        self.label_49.setText(_translate("Dialog", "Page 3", None))
        self.page4Display.setText(_translate("Dialog", "Display", None))
        self.label_50.setText(_translate("Dialog", "Page 4", None))
        self.page5Display.setText(_translate("Dialog", "Display", None))
        self.label_51.setText(_translate("Dialog", "Page 5", None))
        self.page6Display.setText(_translate("Dialog", "Display", None))
        self.label_52.setText(_translate("Dialog", "Page 6", None))

