# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'output_map.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(825, 621)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/background/GenRiver logo.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.landcoverBtn = QtGui.QPushButton(Dialog)
        self.landcoverBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.landcoverBtn.setObjectName(_fromUtf8("landcoverBtn"))
        self.horizontalLayout_5.addWidget(self.landcoverBtn)
        self.subcatchBtn = QtGui.QPushButton(Dialog)
        self.subcatchBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.subcatchBtn.setObjectName(_fromUtf8("subcatchBtn"))
        self.horizontalLayout_5.addWidget(self.subcatchBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.goDayEdit = QtGui.QLineEdit(Dialog)
        self.goDayEdit.setMaximumSize(QtCore.QSize(300, 25))
        self.goDayEdit.setObjectName(_fromUtf8("goDayEdit"))
        self.horizontalLayout.addWidget(self.goDayEdit)
        self.goBtn = QtGui.QPushButton(Dialog)
        self.goBtn.setMaximumSize(QtCore.QSize(100, 25))
        self.goBtn.setObjectName(_fromUtf8("goBtn"))
        self.horizontalLayout.addWidget(self.goBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.backBtn = QtGui.QPushButton(Dialog)
        self.backBtn.setMaximumSize(QtCore.QSize(100, 25))
        self.backBtn.setObjectName(_fromUtf8("backBtn"))
        self.horizontalLayout_2.addWidget(self.backBtn)
        self.dayLCD = QtGui.QLCDNumber(Dialog)
        self.dayLCD.setMaximumSize(QtCore.QSize(100, 25))
        self.dayLCD.setObjectName(_fromUtf8("dayLCD"))
        self.horizontalLayout_2.addWidget(self.dayLCD)
        self.nextBtn = QtGui.QPushButton(Dialog)
        self.nextBtn.setMaximumSize(QtCore.QSize(100, 25))
        self.nextBtn.setObjectName(_fromUtf8("nextBtn"))
        self.horizontalLayout_2.addWidget(self.nextBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_169 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_169.sizePolicy().hasHeightForWidth())
        self.label_169.setSizePolicy(sizePolicy)
        self.label_169.setMaximumSize(QtCore.QSize(50, 25))
        self.label_169.setObjectName(_fromUtf8("label_169"))
        self.horizontalLayout_4.addWidget(self.label_169)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.screen1GroupBox = QtGui.QGroupBox(Dialog)
        self.screen1GroupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.screen1GroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.screen1GroupBox.setObjectName(_fromUtf8("screen1GroupBox"))
        self.subcatchmentRadio = QtGui.QRadioButton(self.screen1GroupBox)
        self.subcatchmentRadio.setGeometry(QtCore.QRect(10, 20, 121, 17))
        self.subcatchmentRadio.setObjectName(_fromUtf8("subcatchmentRadio"))
        self.landcoverRadio = QtGui.QRadioButton(self.screen1GroupBox)
        self.landcoverRadio.setGeometry(QtCore.QRect(10, 50, 111, 17))
        self.landcoverRadio.setObjectName(_fromUtf8("landcoverRadio"))
        self.verticalLayout_2.addWidget(self.screen1GroupBox)
        self.screen2GroupBox = QtGui.QGroupBox(Dialog)
        self.screen2GroupBox.setMinimumSize(QtCore.QSize(100, 100))
        self.screen2GroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.screen2GroupBox.setObjectName(_fromUtf8("screen2GroupBox"))
        self.radioButton = QtGui.QRadioButton(self.screen2GroupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 101, 17))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_3 = QtGui.QRadioButton(self.screen2GroupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 50, 111, 17))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_6 = QtGui.QRadioButton(self.screen2GroupBox)
        self.radioButton_6.setGeometry(QtCore.QRect(150, 20, 82, 17))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.radioButton_7 = QtGui.QRadioButton(self.screen2GroupBox)
        self.radioButton_7.setGeometry(QtCore.QRect(150, 50, 82, 17))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.verticalLayout_2.addWidget(self.screen2GroupBox)
        self.screen3GroupBox = QtGui.QGroupBox(Dialog)
        self.screen3GroupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.screen3GroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.screen3GroupBox.setObjectName(_fromUtf8("screen3GroupBox"))
        self.radioButton_4 = QtGui.QRadioButton(self.screen3GroupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_8 = QtGui.QRadioButton(self.screen3GroupBox)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 50, 101, 17))
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.radioButton_9 = QtGui.QRadioButton(self.screen3GroupBox)
        self.radioButton_9.setGeometry(QtCore.QRect(150, 20, 101, 17))
        self.radioButton_9.setObjectName(_fromUtf8("radioButton_9"))
        self.radioButton_10 = QtGui.QRadioButton(self.screen3GroupBox)
        self.radioButton_10.setGeometry(QtCore.QRect(150, 50, 82, 17))
        self.radioButton_10.setObjectName(_fromUtf8("radioButton_10"))
        self.verticalLayout_2.addWidget(self.screen3GroupBox)
        self.screen4GroupBox = QtGui.QGroupBox(Dialog)
        self.screen4GroupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.screen4GroupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.screen4GroupBox.setObjectName(_fromUtf8("screen4GroupBox"))
        self.radioButton_11 = QtGui.QRadioButton(self.screen4GroupBox)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 20, 101, 17))
        self.radioButton_11.setObjectName(_fromUtf8("radioButton_11"))
        self.radioButton_12 = QtGui.QRadioButton(self.screen4GroupBox)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 50, 82, 17))
        self.radioButton_12.setObjectName(_fromUtf8("radioButton_12"))
        self.radioButton_13 = QtGui.QRadioButton(self.screen4GroupBox)
        self.radioButton_13.setGeometry(QtCore.QRect(150, 20, 82, 17))
        self.radioButton_13.setObjectName(_fromUtf8("radioButton_13"))
        self.radioButton_14 = QtGui.QRadioButton(self.screen4GroupBox)
        self.radioButton_14.setGeometry(QtCore.QRect(150, 50, 101, 17))
        self.radioButton_14.setObjectName(_fromUtf8("radioButton_14"))
        self.verticalLayout_2.addWidget(self.screen4GroupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.displayResult = QtGui.QFrame(Dialog)
        self.displayResult.setMinimumSize(QtCore.QSize(550, 0))
        self.displayResult.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayResult.setFrameShadow(QtGui.QFrame.Raised)
        self.displayResult.setObjectName(_fromUtf8("displayResult"))
        self.horizontalLayout_6.addWidget(self.displayResult)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Output Maps", None))
        self.landcoverBtn.setText(_translate("Dialog", "Landcover info", None))
        self.subcatchBtn.setText(_translate("Dialog", "Subcatchment info", None))
        self.label.setText(_translate("Dialog", "Choose day to go", None))
        self.goBtn.setText(_translate("Dialog", "GO", None))
        self.backBtn.setText(_translate("Dialog", "< Back", None))
        self.nextBtn.setText(_translate("Dialog", "Next >", None))
        self.label_169.setText(_translate("Dialog", "Day", None))
        self.screen1GroupBox.setTitle(_translate("Dialog", "Screen 1", None))
        self.subcatchmentRadio.setText(_translate("Dialog", "Subcatchment map", None))
        self.landcoverRadio.setText(_translate("Dialog", "Landcover map", None))
        self.screen2GroupBox.setTitle(_translate("Dialog", "Screen 2", None))
        self.radioButton.setText(_translate("Dialog", "L_InFlowtoLake", None))
        self.radioButton_3.setText(_translate("Dialog", "O_EvapoTransAcc", None))
        self.radioButton_6.setText(_translate("Dialog", "O_PercAcc", None))
        self.radioButton_7.setText(_translate("Dialog", "O_RainAcc", None))
        self.screen3GroupBox.setTitle(_translate("Dialog", "Screen 3", None))
        self.radioButton_4.setText(_translate("Dialog", "O_SurfQFlowAcc", None))
        self.radioButton_8.setText(_translate("Dialog", "O_BaseFlowAcc", None))
        self.radioButton_9.setText(_translate("Dialog", "O_DeepInfAcc", None))
        self.radioButton_10.setText(_translate("Dialog", "O_IntercAcc", None))
        self.screen4GroupBox.setTitle(_translate("Dialog", "Screen 4", None))
        self.radioButton_11.setText(_translate("Dialog", "O_SoilQFlowAcc", None))
        self.radioButton_12.setText(_translate("Dialog", "O_InfAcc", None))
        self.radioButton_13.setText(_translate("Dialog", "D_GWaDisch", None))
        self.radioButton_14.setText(_translate("Dialog", "D_SoilDischarge", None))

import images_rc
