# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'output_timeseries.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1076, 618)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_168 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_168.sizePolicy().hasHeightForWidth())
        self.label_168.setSizePolicy(sizePolicy)
        self.label_168.setMaximumSize(QtCore.QSize(200, 20))
        self.label_168.setObjectName(_fromUtf8("label_168"))
        self.verticalLayout.addWidget(self.label_168)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_169 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_169.sizePolicy().hasHeightForWidth())
        self.label_169.setSizePolicy(sizePolicy)
        self.label_169.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_169.setObjectName(_fromUtf8("label_169"))
        self.horizontalLayout.addWidget(self.label_169)
        self.dayProgress = QtGui.QLCDNumber(Dialog)
        self.dayProgress.setMaximumSize(QtCore.QSize(100, 30))
        self.dayProgress.setObjectName(_fromUtf8("dayProgress"))
        self.horizontalLayout.addWidget(self.dayProgress)
        self.label_170 = QtGui.QLabel(Dialog)
        self.label_170.setMaximumSize(QtCore.QSize(200, 20))
        self.label_170.setObjectName(_fromUtf8("label_170"))
        self.horizontalLayout.addWidget(self.label_170)
        self.yearProgress = QtGui.QLCDNumber(Dialog)
        self.yearProgress.setMaximumSize(QtCore.QSize(100, 30))
        self.yearProgress.setObjectName(_fromUtf8("yearProgress"))
        self.horizontalLayout.addWidget(self.yearProgress)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 460))
        self.groupBox_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.page1Btn = QtGui.QPushButton(self.groupBox_2)
        self.page1Btn.setGeometry(QtCore.QRect(0, 20, 75, 23))
        self.page1Btn.setObjectName(_fromUtf8("page1Btn"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.page2Btn = QtGui.QPushButton(self.groupBox_2)
        self.page2Btn.setGeometry(QtCore.QRect(0, 90, 75, 23))
        self.page2Btn.setObjectName(_fromUtf8("page2Btn"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 71, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 160, 91, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(120, 120, 81, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(120, 140, 46, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.page3Btn = QtGui.QPushButton(self.groupBox_2)
        self.page3Btn.setGeometry(QtCore.QRect(0, 180, 75, 23))
        self.page3Btn.setObjectName(_fromUtf8("page3Btn"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 210, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 230, 81, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 250, 81, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(120, 210, 46, 13))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(120, 230, 81, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.page4Btn = QtGui.QPushButton(self.groupBox_2)
        self.page4Btn.setGeometry(QtCore.QRect(0, 270, 75, 23))
        self.page4Btn.setObjectName(_fromUtf8("page4Btn"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 300, 61, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 340, 101, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 320, 91, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(120, 300, 91, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(120, 320, 91, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.page5Btn = QtGui.QPushButton(self.groupBox_2)
        self.page5Btn.setGeometry(QtCore.QRect(0, 360, 75, 23))
        self.page5Btn.setObjectName(_fromUtf8("page5Btn"))
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(10, 390, 71, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(10, 410, 101, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(10, 430, 91, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(120, 390, 81, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(120, 410, 91, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(120, 20, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(120, 40, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.groupBox_2.raise_()
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.displayResult = QtGui.QFrame(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayResult.sizePolicy().hasHeightForWidth())
        self.displayResult.setSizePolicy(sizePolicy)
        self.displayResult.setMinimumSize(QtCore.QSize(800, 600))
        self.displayResult.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayResult.setFrameShadow(QtGui.QFrame.Raised)
        self.displayResult.setObjectName(_fromUtf8("displayResult"))
        self.gridLayout_2.addWidget(self.displayResult, 0, 1, 1, 1)
        self.label_168.raise_()
        self.displayResult.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Output Timeseries", None))
        self.label_168.setText(_translate("Dialog", "Simulation progress", None))
        self.label_169.setText(_translate("Dialog", "Day", None))
        self.label_170.setText(_translate("Dialog", "Year", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Water Balance", None))
        self.page1Btn.setText(_translate("Dialog", "Page 1", None))
        self.label_5.setText(_translate("Dialog", "I_RFlowdata_mmday", None))
        self.label_6.setText(_translate("Dialog", "L_InFlowtoLake", None))
        self.page2Btn.setText(_translate("Dialog", "Page 2", None))
        self.label_7.setText(_translate("Dialog", "O_RainAcc", None))
        self.label_8.setText(_translate("Dialog", "O_IntercAcc", None))
        self.label_9.setText(_translate("Dialog", "O_EvapoTransAcc", None))
        self.label_10.setText(_translate("Dialog", "O_SurfQFlowAcc", None))
        self.label_11.setText(_translate("Dialog", "O_InfAcc", None))
        self.page3Btn.setText(_translate("Dialog", "Page 3", None))
        self.label_12.setText(_translate("Dialog", "O_RainAcc", None))
        self.label_13.setText(_translate("Dialog", "O_DeepInfAcc", None))
        self.label_14.setText(_translate("Dialog", "O_BaseFlowAcc", None))
        self.label_15.setText(_translate("Dialog", "O_PercAcc", None))
        self.label_16.setText(_translate("Dialog", "O_SoilQFlowAcc", None))
        self.page4Btn.setText(_translate("Dialog", "Page 4", None))
        self.label_17.setText(_translate("Dialog", "O_CumRain", None))
        self.label_18.setText(_translate("Dialog", "O_CumIntercepEvap", None))
        self.label_19.setText(_translate("Dialog", "O_CumEvapotrans", None))
        self.label_20.setText(_translate("Dialog", "O_CumSurfQFlow", None))
        self.label_21.setText(_translate("Dialog", "O_CumInfiltration", None))
        self.page5Btn.setText(_translate("Dialog", "Page 5", None))
        self.label_22.setText(_translate("Dialog", "O_CumRain", None))
        self.label_23.setText(_translate("Dialog", "O_CumPercolation", None))
        self.label_24.setText(_translate("Dialog", "O_CumDeepInfilt", None))
        self.label_25.setText(_translate("Dialog", "O_CumBaseFlow", None))
        self.label_26.setText(_translate("Dialog", "O_CumSoilQFlow", None))
        self.groupBox.setTitle(_translate("Dialog", "HEEP", None))
        self.label.setText(_translate("Dialog", "L_HEPPWatUseFlow", None))
        self.label_2.setText(_translate("Dialog", "L_LakeVol", None))
        self.label_3.setText(_translate("Dialog", "L_HEPP_Kwh", None))
        self.label_4.setText(_translate("Dialog", "L_LakeLevel", None))

